- name: Create RabbitMQ vhost
  hosts: localhost
  connection: local
  tasks:
    - name: Install RabbitMQ management plugin
      become: yes
      apt:
        name: rabbitmq-server
        state: present
    - name: Enable RabbitMQ management plugin
      become: yes
      shell: rabbitmq-plugins enable rabbitmq_management

